seed: null
debug: false

trainer:
  experiment_name: {{cookiecutter.project_name}}
  experiment_description: |
    {{cookiecutter.experiment_description}}
    This experiment tests the model with ...
    Feel free to be way more verbose here

  tags: []
  max_epochs: 100

data:
  batch_size: 64
  batch_size_eval: 128
  num_workers: 1

optimizer: Adam
optim:
  lr: !float 1e-3
  weight_decay: !float 1e-2

lr_scheduler: true
lr_schedule:
  factor: 2

model:
  # Your model parameters go here.
